id = "flou-extension"
name = "Flou"
version = "0.0.1"
schema_version = 1
authors = ["Mika AÃŸmus mika.assmus@gmail.com"]
description = "Support for the Flou Programming Language"
repository = "https://github.com/mikatschuh/flou-extension"

[grammars.flou]
repository = "https://github.com/mikatschuh/tree-sitter-flou"
rev = "6e450c6297c2e90d955245250f89cecb85289d05"
