id = "rux-extension"
name = "Rux extension"
version = "0.0.1"
schema_version = 1
authors = ["Mika AÃŸmus mika.assmus@gmail.com"]
description = "Rux support."
repository = "https://github.com/mikatschuh/rux-extension"

[grammars.rux]
repository = "https://github.com/mikatschuh/tree-sitter-rux"
rev = "ee79f2a8f248eeea028d4044b81ff4466be8319f"
